version: '3'

services:
    app:
        image: php:8.2-cli-alpine
        working_dir: /app
        container_name: app
        entrypoint: sh
        tty: true
        volumes:
            - .:/app
    composer:
        image: composer:latest
        working_dir: /app
        container_name: composer
        entrypoint: sh
        tty: true
        volumes:
            - .:/app
