version: '3'

services:
    app:
        build:
            context: docker/php
        working_dir: /usr/src/app
        container_name: app
        entrypoint: bash
        tty: true
        volumes:
            - .:/usr/src/app
